#!/usr/bin/env bash
# Cockpit — first-time install on a WHM server
# Run as root on the WHM server.
# Pass any env var as CLI flag (e.g. WHM_TOKEN=abc) to skip its prompt.
set -euo pipefail

COCKPIT_USER="cockpit"
COCKPIT_HOME="/var/lib/cockpit"
COCKPIT_CONFIG="/etc/cockpit"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "================================================"
echo "  Cockpit — Interactive Install"
echo "================================================"
echo ""

# ── Prompt for required config ──────────────────────────────────────────

prompt() {
  local var="$1" label="$2" default="${3:-}" secret="${4:-}"
  local val="${!var:-}"
  if [ -n "$val" ]; then
    echo "  $label: $val (from env)"
    return
  fi
  local prompt_str="$label"
  [ -n "$default" ] && prompt_str="$prompt_str [$default]"
  if [ "$secret" = "secret" ]; then
    read -r -s -p "  $prompt_str: " val
    echo ""
  else
    read -r -p "  $prompt_str: " val
  fi
  val="${val:-$default}"
  printf -v "$var" "%s" "$val"
}

echo "── WHM API ──"
echo "  (Generate a token in WHM → API Tokens → Generate)"
prompt WHM_TOKEN "WHM API token" "" "secret"
prompt WHM_HOST "WHM host" "localhost"
prompt WHM_PORT "WHM port" "2087"

echo ""
echo "── Client Telemetry API (used by WHMCS) ──"
echo "  This key is shared between Cockpit and your Next.js server."
prompt CLIENT_API_KEY "Client API key (generate one)" "cockpit-$(openssl rand -hex 16)"
echo "  → Key: $CLIENT_API_KEY"

echo ""
echo "── OpenAI / Codex (optional, Phase 6) ──"
prompt OPENAI_API_KEY "OpenAI API key (leave blank to skip)" "" "secret"
prompt OPENAI_MODEL "OpenAI model" "gpt-4o"

echo ""
echo "── Dashboard ──"
prompt DASHBOARD_HOST "Dashboard bind host" "127.0.0.1"
prompt DASHBOARD_PORT "Dashboard port" "8080"
prompt TAILSCALE_AUTH "Require Tailscale auth?" "true"

echo ""
echo "── Client API ──"
prompt CLIENT_API_HOST "Client API bind host" "127.0.0.1"
prompt CLIENT_API_PORT "Client API port" "8081"

# ── Write env file ──────────────────────────────────────────────────────

echo ""
echo "==> Writing $COCKPIT_CONFIG/cockpit.env"
mkdir -p "$COCKPIT_CONFIG"

cat > "$COCKPIT_CONFIG/cockpit.env" <<ENVEOF
# Cockpit — generated by install.sh
COCKPIT_DB_PATH=$COCKPIT_HOME/cockpit.db
COCKPIT_WHM_HOST=$WHM_HOST
COCKPIT_WHM_PORT=$WHM_PORT
COCKPIT_WHM_TOKEN=$WHM_TOKEN
COCKPIT_DASHBOARD_HOST=$DASHBOARD_HOST
COCKPIT_DASHBOARD_PORT=$DASHBOARD_PORT
COCKPIT_TAILSCALE_AUTH_ENABLED=$TAILSCALE_AUTH
COCKPIT_CLIENT_API_KEY=$CLIENT_API_KEY
COCKPIT_CLIENT_API_HOST=$CLIENT_API_HOST
COCKPIT_CLIENT_API_PORT=$CLIENT_API_PORT
COCKPIT_OPENAI_API_KEY=$OPENAI_API_KEY
COCKPIT_OPENAI_MODEL=$OPENAI_MODEL
COCKPIT_POLICY_PATH=$COCKPIT_CONFIG/policy.toml
ENVEOF

chown root:root "$COCKPIT_CONFIG/cockpit.env"
chmod 600 "$COCKPIT_CONFIG/cockpit.env"

# ── System setup ────────────────────────────────────────────────────────

echo "==> Creating cockpit system user"
id -u "$COCKPIT_USER" &>/dev/null || useradd --system --no-create-home --shell /usr/sbin/nologin "$COCKPIT_USER"

echo "==> Creating data directory"
mkdir -p "$COCKPIT_HOME"
chown "$COCKPIT_USER":"$COCKPIT_USER" "$COCKPIT_HOME"
chmod 750 "$COCKPIT_HOME"

echo "==> Installing Python package"
pip install "$REPO_DIR"

echo "==> Installing default policy file"
if [ ! -f "$COCKPIT_CONFIG/policy.toml" ]; then
  cp "$REPO_DIR/config/policy.example.toml" "$COCKPIT_CONFIG/policy.toml"
  chown root:root "$COCKPIT_CONFIG/policy.toml"
  chmod 644 "$COCKPIT_CONFIG/policy.toml"
fi

echo "==> Installing systemd units"
for unit in cockpit-collector cockpit-dashboard cockpit-client-api; do
  cp "$REPO_DIR/deploy/${unit}.service" /etc/systemd/system/
  chmod 644 "/etc/systemd/system/${unit}.service"
done
systemctl daemon-reload

echo "==> Running database migration"
sudo -u "$COCKPIT_USER" COCKPIT_DB_PATH="$COCKPIT_HOME/cockpit.db" cockpit-db-migrate

echo "==> Enabling and starting services"
systemctl enable --now cockpit-collector cockpit-dashboard cockpit-client-api

echo ""
echo "================================================"
echo "  ✅ Cockpit installed successfully"
echo "================================================"
echo ""
echo "  Dashboard:  http://$DASHBOARD_HOST:$DASHBOARD_PORT"
echo "  Client API: http://$CLIENT_API_HOST:$CLIENT_API_PORT"
echo "  WHM API:    $WHM_HOST:$WHM_PORT"
echo "  DB:         $COCKPIT_HOME/cockpit.db"
echo ""
echo "  Config:     $COCKPIT_CONFIG/cockpit.env (chmod 600)"
echo "  Policy:     $COCKPIT_CONFIG/policy.toml"
echo ""
echo "  Client API key (for Next.js env): $CLIENT_API_KEY"
echo ""
echo "  Next:"
echo "    1. Set COCKPIT_CLIENT_API_KEY=$CLIENT_API_KEY"
echo "       in your Next.js server environment"
echo "    2. Configure Tailscale funnel / reverse proxy for"
echo "       the dashboard if you need external access"
echo "    3. Check logs: journalctl -u cockpit-collector -f"
echo ""
